services:
  postgres:
    container_name: vtz-db-postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./pgdata/data:/var/lib/postgresql/data
    networks:
      - vtz-network

  pgadmin:
    container_name: vtz-db-pgadmin
    image: dpage/pgadmin4
    volumes:
      - ./pgdata/pgadmin:/root/.pgadmin
    env_file:
      - .env
    hostname: pgadmin
    ports:
      - ${PG_ADMIN_PORT}:80
    logging:
      driver: none
    networks:
      - vtz-network

  backend:
    build: ./back
    container_name: back
    ports:
      - 7217:7217
      - 5000:8080
    depends_on:
      - postgres
      - pgadmin
    restart: unless-stopped
    networks:
      - vtz-network

#  front:
#    build: ./front
#    container_name: front
#    ports:
#      - ${FRONT_APP_PORT}:3000
#    networks:
#      - vtz-network

networks:
  vtz-network:
    driver: bridge
